# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

<<<<<<< HEAD
index = {}
=======
index = {"read_image": "00_core.ipynb",
         "LOLA_DEM": "01_dems.ipynb"}
>>>>>>> current status

modules = ["core.py",
           "dems.py"]

doc_url = "https://michaelaye.github.io/trex_diviner_pipeline/"

git_url = "https://github.com/michaelaye/trex_diviner_pipeline/tree/master/"

def custom_doc_links(name): return None
