# AUTOGENERATED! DO NOT EDIT! File to edit: 00_core.ipynb (unless otherwise specified).

<<<<<<< HEAD
__all__ = []
=======
__all__ = ['read_image']
>>>>>>> current status

# Cell
import math
from dataclasses import dataclass, field
from pathlib import Path, PosixPath
from typing import List

import heat1d
import planets
import xarray as xr
from heat1d.plotting import plot_last_surface_cooling
<<<<<<< HEAD
from scipy.spatial.distance import pdist, squareform
=======
from scipy.spatial.distance import pdist, squareform

import heat1d


# Cell
def read_image(fpath, chunk_scale=2):
    cycle = int(fpath.name.split("_")[4][:-1])
    da = xr.open_rasterio(
        fpath, chunks={"x": chunk_scale * 2048, "y": chunk_scale * 1024}
    )
    da = da.assign_coords(band=[cycle])
    return da.rename({"band": "time"})
>>>>>>> current status
